### ISSUE TITLE
about IndexError : list index out of range

### ISSUE THREAD

**Issue by prince-Ha** [eroots/gams#5]
Hi, I read your gams article in Seg.

content was useful, so I applied it to my data 

but ... error is occur when I input and excute the data

IndexError : list index out of range

below picture is my situation![image](https://user-images.githubusercontent.com/69688086/201526782-af2e81b4-914e-4acb-8d8d-2f66920c51c0.png)

![image](https://user-images.githubusercontent.com/69688086/201526795-9f96845b-48c1-4327-9572-0bdf19d72080.png)

![image](https://user-images.githubusercontent.com/69688086/201526850-4946ef0f-fc61-4f8d-a1a0-816ec49df17f.png)

thanks

**Comment by eroots** [comment]
I can't see why this error would be happening unless the grid you're loading has no fields.
Are you able to send

**Comment by prince-Ha** [comment]
I wonder what's wrong
Please check

thanks

2022년 11월 13일 (일) 오후 11:53, eroots ***@***.***>님이 작성:

**Comment by eroots** [comment]
Sorry, accidently closed the issue and re-opened.

> I can't see why this error would be happening unless the grid you're loading has no fields.
> Are you able to send the geoh5 file so I can test?

**Comment by prince-Ha** [comment]
Did you receive the geoh5 file?

**Comment by eroots** [comment]
No I haven't received anything.

**Comment by prince-Ha** [comment]
I attached the file when I replied to the email, but I guess it didn't go And github can't upload geoh5 format, so where should I send the file?

**Comment by eroots** [comment]
Github should let you attach it if its zipped

**Comment by prince-Ha** [comment]
> Github should let you attach it if its zipped
ah.. thank you : )
[EMAG2.zip](https://github.com/eroots/gams/files/10003591/EMAG2.zip)

**Comment by eroots** [comment]
OK I see the issue.
Your grid name is different from the field name that you want to load (Up2_Residual vs. Band 1). The program expects them to be named the same thing.
Its probably reasonable that these could named differently so I'll work on a solution, but in the meantime if you rename 'Band 1' to 'Up2_Residual' (or vice-versa) and save the workspace then things should work.

**Comment by prince-Ha** [comment]
oh.. 
program works well. : )
thanks to your program I can continue to write the paper

I know you're busy, but please tell me one more thing

how to write the ASCII format data ?
